default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aws_rekognition_development

test:
  <<: *default
  database: aws_rekognition_test

production:
  <<: *default
  database: aws_rekognition_production
  username: aws_rekognition
  password: <%= ENV["AWS_REKOGNITION_DATABASE_PASSWORD"] %>
